<a href="https://colab.research.google.com/github/sadiksha1920/DSA/blob/master/001pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

#creating series with list
l=[1,2,3,4,5]
s= pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [2]:
#we can also change the index of series by
l=[1,2,3,4,5]
s=pd.Series(l,index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [3]:
#creating Series with Array
import numpy as np
a= np.array([80,20,78])
s=pd.Series(a)
s

0    80
1    20
2    78
dtype: int64

In [4]:
#creating series with dictionary
d={'name':'sadiksha','roll':1,'age':22}
s=pd.Series(d)
s

name    sadiksha
roll           1
age           22
dtype: object

Attribute for Series

In [5]:
s= pd.Series(['sadiksha','binita','Garima','shiwani'],index=['a','b','c','d'])
s

a    sadiksha
b      binita
c      Garima
d     shiwani
dtype: object

In [6]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [7]:
s.array

<NumpyExtensionArray>
['sadiksha', 'binita', 'Garima', 'shiwani']
Length: 4, dtype: object

In [8]:
#using dtype attributes  gives what is the data type of element of this series
s.dtype

dtype('O')

In [9]:
#using values attribute 9returns values of series in numpy array
s.values

array(['sadiksha', 'binita', 'Garima', 'shiwani'], dtype=object)

In [10]:
#using shape attribute (for series shape 4 represent the 4 rows)
#for series s.shape also help us to find the numbers of elements in the series like s.size
s.shape

(4,)

In [11]:
s.ndim

1

In [12]:
s.size #total number of element

4

In [13]:
s.empty

False

In [14]:
s

a    sadiksha
b      binita
c      Garima
d     shiwani
dtype: object

In [15]:
s['a']

'sadiksha'

In [16]:
s.at['a']

'sadiksha'

In [17]:
s.iat[0] #we have to pass index

'sadiksha'

In [18]:
s.iat[3]

'shiwani'

Mathematical operation in Series

In [19]:
a=[1,2,3]
b=[2,3,4]
c=a+b
c

[1, 2, 3, 2, 3, 4]

In [20]:
import pandas as pd
s1=pd.Series([1,2,3])
s2=pd.Series([2,3,4])

In [21]:


#add
s1+s2

0    3
1    5
2    7
dtype: int64

In [22]:
s1-s2

0   -1
1   -1
2   -1
dtype: int64

In [23]:
s1*s2

0     2
1     6
2    12
dtype: int64

In [24]:
s1/s2

0    0.500000
1    0.666667
2    0.750000
dtype: float64

In [25]:

s1**s2

0     1
1     8
2    81
dtype: int64

In [26]:

s1>s2

0    False
1    False
2    False
dtype: bool

In [27]:
s1==s2

0    False
1    False
2    False
dtype: bool

In [28]:
s.dtype

dtype('O')

Getting value from the series

In [29]:
import pandas as pd
s= pd.Series([1,2,3,4,6])
s

0    1
1    2
2    3
3    4
4    6
dtype: int64

In [30]:
print(s[3]) # getting index 3 value

4

In [31]:
s[1:3]# getting index 1 and 2 element

1    2
2    3
dtype: int64

In [32]:
s.index=['a','b','c','d','e']
s

a    1
b    2
c    3
d    4
e    6
dtype: int64

In [33]:
print(s['d'])

4

B) DataFrame - Data Frame is the 2D Data Structure (tabluar form)
Different ways of Creating Data Frame in pandas

By reading data from Excel File

By reading data from CSV File (comma seperated values)

BY using Dictionary

In [34]:
#making dataframe by reading excel
df=pd.read_excel(r"/content/excel_df.xlsx")

FileNotFoundError: [Errno 2] No such file or directory: '/content/excel_df.xlsx'

In [35]:
df

NameError: name 'df' is not defined

In [36]:
#making dataframe by reading csv
df=pd.read_csv(r"/content/new_data.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/new_data.csv'

In [37]:
#making dataframe by using dictionary
dict ={'name':['sadiksha','garima','binita','sita','gita'],'roll':[1,2,3,4,5],'age':[13,14,15,23,24]}
df=pd.DataFrame(dict)
df

       name  roll  age
0  sadiksha     1   13
1    garima     2   14
2    binita     3   15
3      sita     4   23
4      gita     5   24

In [38]:
df

       name  roll  age
0  sadiksha     1   13
1    garima     2   14
2    binita     3   15
3      sita     4   23
4      gita     5   24

In [39]:
df.T

             0       1       2     3     4
name  sadiksha  garima  binita  sita  gita
roll         1       2       3     4     5
age         13      14      15    23    24

In [40]:
df

       name  roll  age
0  sadiksha     1   13
1    garima     2   14
2    binita     3   15
3      sita     4   23
4      gita     5   24

In [41]:
print(df.at[1,'name']) # use label and get single value

garima

In [42]:
print(df.iat[0,0])

sadiksha

In [43]:
df

       name  roll  age
0  sadiksha     1   13
1    garima     2   14
2    binita     3   15
3      sita     4   23
4      gita     5   24

In [44]:
df.index
df.index=['a','b','c','d','e']
df

       name  roll  age
a  sadiksha     1   13
b    garima     2   14
c    binita     3   15
d      sita     4   23
e      gita     5   24

In [45]:
df.axes

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object'),
 Index(['name', 'roll', 'age'], dtype='object')]

In [46]:
df.axes[0] #row names

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [47]:
df.axes[1]#column names

Index(['name', 'roll', 'age'], dtype='object')

In [48]:
df

       name  roll  age
a  sadiksha     1   13
b    garima     2   14
c    binita     3   15
d      sita     4   23
e      gita     5   24

In [49]:
df.columns

Index(['name', 'roll', 'age'], dtype='object')

In [50]:
df.dtypes # returns what type od data is sorted by each columns in data frame

name    object
roll     int64
age      int64
dtype: object

In [51]:
df.ndim #dimension of the dataframe

2

In [52]:
df.shape# return number of rows and number of columns

(5, 3)

In [53]:
df.size #gives the number of elements in the data frame

15

In [54]:
df

       name  roll  age
a  sadiksha     1   13
b    garima     2   14
c    binita     3   15
d      sita     4   23
e      gita     5   24

In [55]:
df.values # converts the numpy dataframe into numpy array

array([['sadiksha', 1, 13],
       ['garima', 2, 14],
       ['binita', 3, 15],
       ['sita', 4, 23],
       ['gita', 5, 24]], dtype=object)

Important Methods() for DataFrame
value_counts() – Returns how many times each unique value is repeated in a Series.

df['column'].value_counts()
to_dict() – Converts a Series or DataFrame into a Python dictionary.

sort_index() – Sorts a Series or DataFrame by its index in ascending order.

sort_values() – Sorts a Series or DataFrame by its values in ascending order.

set_index() – Sets an existing column as the index of a DataFrame.

reset_index() – Resets the index of a DataFrame and converts the index into a regular column. Creates a new DataFrame with a default index.

replace() – Replaces specified values in a Series or DataFrame with other values.

rename() – Renames row index labels or column labels of a Series or DataFrame.

query() – Filters a DataFrame using a Boolean expression and returns a new DataFrame containing the matching rows.

notna() – Returns True for non-null values and False for null values.

nsmallest() – Returns the n smallest values from a Series or DataFrame.

nlargest() – Returns the n largest values from a Series or DataFrame.

nunique() – Counts the number of unique values present in a column.

info() – Provides a concise summary of a DataFrame, including data types, non-null values, and memory usage.

describe() – Generates descriptive statistics of a DataFrame, including count, mean, standard deviation, minimum, maximum, and quartile values.

count() – Counts the number of non-null values in each column of a DataFrame.

copy() – Creates a deep copy of a Series or DataFrame.

In [56]:
df['age'].value_counts()

age
13    1
14    1
15    1
23    1
24    1
Name: count, dtype: int64

In [57]:
df['name'].value_counts()

name
sadiksha    1
garima      1
binita      1
sita        1
gita        1
Name: count, dtype: int64

In [58]:
#convert the dataframe into dictionary
df.to_dict()

{'name': {'a': 'sadiksha',
  'b': 'garima',
  'c': 'binita',
  'd': 'sita',
  'e': 'gita'},
 'roll': {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
 'age': {'a': 13, 'b': 14, 'c': 15, 'd': 23, 'e': 24}}

In [59]:
df

       name  roll  age
a  sadiksha     1   13
b    garima     2   14
c    binita     3   15
d      sita     4   23
e      gita     5   24

In [60]:
#we can also convert dataframe into json
df.to_json('new_data.json')

In [61]:
df=pd.read_json("new_data.json")

In [62]:
df.index=['b','a','d','c','e']
df.sort_index(ascending =False)

       name  roll  age
e      gita     5   24
d    binita     3   15
c      sita     4   23
b  sadiksha     1   13
a    garima     2   14

In [63]:
df.sort_index()

       name  roll  age
a    garima     2   14
b  sadiksha     1   13
c      sita     4   23
d    binita     3   15
e      gita     5   24

In [64]:
#setting the existing column to index
df.set_index("age")

         name  roll
age
13   sadiksha     1
14     garima     2
15     binita     3
23       sita     4
24       gita     5

In [65]:
df.set_index("roll")

          name  age
roll
1     sadiksha   13
2       garima   14
3       binita   15
4         sita   23
5         gita   24

In [66]:
#reset the index to default one
df.reset_index()

  index      name  roll  age
0     b  sadiksha     1   13
1     a    garima     2   14
2     d    binita     3   15
3     c      sita     4   23
4     e      gita     5   24

In [67]:
df.reset_index(drop=True)# drop the extra index

       name  roll  age
0  sadiksha     1   13
1    garima     2   14
2    binita     3   15
3      sita     4   23
4      gita     5   24

In [68]:
#dataframe which consist nan values

data={'Name':['sadiksha',np.nan,'anu'],
     'Age':[20,22,np.nan],
     'Height':[175,162,np.nan]}
df=pd.DataFrame(data)
df

       Name   Age  Height
0  sadiksha  20.0   175.0
1       NaN  22.0   162.0
2       anu   NaN     NaN

In [69]:
#replace the nan value with none
df.replace(np.nan,None,inplace=True)

In [70]:
df

       Name   Age Height
0  sadiksha  20.0  175.0
1      None  22.0  162.0
2       anu  None   None

In [71]:
#replacing anu with miraj
df.replace('anu','miraj',inplace=True)

In [72]:
df

       Name   Age Height
0  sadiksha  20.0  175.0
1      None  22.0  162.0
2     miraj  None   None

In [73]:
# performing the query() function in the dataframe

# Create a sample DataFrame
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
'Age': [25, 28, 22, 30],
'Height': [175, 162, 180, 168]}
df = pd.DataFrame(data)
# Print the original DataFrame
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name  Age  Height
0     John   25     175
1     Emma   28     162
2  Michael   22     180
3   Sophia   30     168

In [74]:
filtered_df1= df.query("Age>25 and Height<170")
filtered_df2=df.query("Name=='john'")
filtered_df3=df.query("Name in ['John','Emma']")# select row where name is either 'John' or'Emma'
filtered_df4 = df.query("not Height<=168") #select rows where height is not lesser equal to 168
filtered_df5= df.query("Name.str.startswith('S')")
#Print the filtered pd.DataFrame
print('\n')
print(filtered_df1)
print('\n')
print(filtered_df2)
print('\n')
print(filtered_df3)
print('\n')
print(filtered_df4)
print('\n')
print(filtered_df5)

     Name  Age  Height
1    Emma   28     162
3  Sophia   30     168


Empty DataFrame
Columns: [Name, Age, Height]
Index: []


   Name  Age  Height
0  John   25     175
1  Emma   28     162


      Name  Age  Height
0     John   25     175
2  Michael   22     180


     Name  Age  Height
3  Sophia   30     168

In [75]:
# Create a sample DataFrame with missing values
data = {'Name': ['John', np.nan, 'Michael'],
'Age': [25, np.nan, 22],
'Height': [175, 162, np.nan]}
df = pd.DataFrame(data)
df

      Name   Age  Height
0     John  25.0   175.0
1      NaN   NaN   162.0
2  Michael  22.0     NaN

In [76]:
df['Name'].notna()

0     True
1    False
2     True
Name: Name, dtype: bool

In [77]:
df['Age'].notna()#return boolean value if there is value in dataframe

0     True
1    False
2     True
Name: Age, dtype: bool

In [78]:
df[df['Name'].notna()]

      Name   Age  Height
0     John  25.0   175.0
2  Michael  22.0     NaN

In [79]:
# just creating a data frame
dict = {'name':['miraj','sabal','sarita','rashmi','sabnam'],
'roll':[1,2,3,4,5] ,'age':[13,34,32,54,32] }
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [80]:
s= df.nsmallest(2,'age')##age column ko 2 ota smallest value dinxa

In [81]:
l=df.nlargest(2,'age')
l

     name  roll  age
3  rashmi     4   54
1   sabal     2   34

In [82]:
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   roll    5 non-null      int64
 2   age     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [84]:
df.describe()
#This method generates descriptive statistics of a DataFrame,
#including count, mean, standard deviation, minimum, maximum, and quartile values.

           roll        age
count  5.000000   5.000000
mean   3.000000  33.000000
std    1.581139  14.525839
min    1.000000  13.000000
25%    2.000000  32.000000
50%    3.000000  32.000000
75%    4.000000  34.000000
max    5.000000  54.000000

In [85]:
df.count()

name    5
roll    5
age     5
dtype: int64

In [86]:
#copying the dataframe into m
m=df.copy()
m

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [87]:
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [88]:
m

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [89]:
df.nunique()

name    5
roll    5
age     4
dtype: int64

IMP Functions, Accessing values, Slicing in data frame