<a href="https://colab.research.google.com/github/sadiksha1920/DSA/blob/master/day1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
files.upload()

Saving dirty_cafe_sales.csv to dirty_cafe_sales.csv

{'dirty_cafe_sales.csv': b'Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date\r\nTXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08\r\nTXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16\r\nTXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19\r\nTXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27\r\nTXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11\r\nTXN_2602893,Smoothie,5,4.0,20.0,Credit Card,,2023-03-31\r\nTXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06\r\nTXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28\r\nTXN_4717867,,5,3.0,15.0,,Takeaway,2023-07-28\r\nTXN_2064365,Sandwich,5,4.0,20.0,,In-store,2023-12-31\r\nTXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07\r\nTXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR\r\nTXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03\r\nTXN_9437049,Cookie,5,1.0,5.0,,Takeaway,2023-06-01\r\nTXN_8915701,ERROR,2,1.5,3.0,,In-store,2023-03-21\r\nTXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15\r\nTXN_3765707,Sandwich,1,4.0,4.0,,,2023-06-10\r\nTXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24\r\nTXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25\r\nTXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15\r\nTXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04\r\nTXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30\r\nTXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01\r\nTXN_2616390,Sandwich,2,4.0,8.0,,,2023-09-18\r\nTXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03\r\nTXN_7958992,Smoothie,3,4.0,,UNKNOWN,UNKNOWN,2023-12-13\r\nTXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20\r\nTXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10\r\nTXN_8467949,Smoothie,5,4.0,20.0,Credit Card,,2023-03-11\r\nTXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR\r\nTXN_1736287,,5,2.0,10.0,Digital Wallet,,2023-06-02\r\nTXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06\r\nTXN_9677376,Smoothie,4,4.0,16.0,,In-store,2023-08-15\r\nTXN_7710508,UNKNOWN,5,1.0,5.0,Cash,,ERROR\r\nTXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09\r\nTXN_9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28\r\nTXN_6855453,UNKNOWN,4,3.0,12.0,,In-store,2023-07-17\r\nTXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29\r\nTXN_2655815,Smoothie,4,4.0,16.0,,Takeaway,2023-06-08\r\nTXN_6688524,Coffee,4,2.0,8.0,ERROR,,2023-06-29\r\nTXN_2083138,Smoothie,3,4.0,12.0,,In-store,2023-04-17\r\nTXN_2427584,Sandwich,4,4.0,16.0,,Takeaway,2023-12-22\r\nTXN_6650263,Tea,2,1.5,UNKNOWN,,Takeaway,2023-01-10\r\nTXN_9620080,Juice,4,3.0,12.0,,Takeaway,2023-10-02\r\nTXN_1491578,Cookie,2,1.0,2.0,,,2023-02-23\r\nTXN_5455792,Salad,3,5.0,15.0,Cash,,2023-03-22\r\nTXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03\r\nTXN_9499313,Juice,5,3.0,15.0,,,2023-03-02\r\nTXN_8201146,Juice,5,3.0,15.0,Cash,,2023-06-26\r\nTXN_8230936,Cake,3,3.0,9.0,,ERROR,2023-05-02\r\nTXN_7742742,Cake,5,3.0,15.0,,Takeaway,2023-09-05\r\nTXN_6342161,Salad,5,5.0,25.0,ERROR,Takeaway,2023-01-08\r\nTXN_8914892,UNKNOWN,5,5.0,25.0,Digital Wallet,,2023-03-15\r\nTXN_3363746,Smoothie,3,4.0,12.0,Credit Card,,2023-11-25\r\nTXN_8614868,Smoothie,5,4.0,20.0,Digital Wallet,Takeaway,2023-12-05\r\nTXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19\r\nTXN_3578141,Cake,5,,15.0,,Takeaway,2023-06-27\r\nTXN_2080895,Cake,UNKNOWN,3.0,3.0,Digital Wallet,In-store,2023-04-19\r\nTXN_6421134,Sandwich,4,4.0,16.0,Cash,Takeaway,2023-11-03\r\nTXN_8813311,Juice,5,3.0,15.0,,In-store,2023-10-07\r\nTXN_9023317,Salad,1,5.0,5.0,,,2023-09-30\r\nTXN_8051289,,1,3.0,3.0,,In-store,2023-10-09\r\nTXN_2537617,Sandwich,1,4.0,4.0,Cash,,2023-05-27\r\nTXN_9099694,UNKNOWN,3,5.0,15.0,,Takeaway,2023-11-18\r\nTXN_9230615,Smoothie,4,4.0,16.0,Digital Wallet,,2023-06-01\r\nTXN_4987129,Sandwich,3,,,,In-store,2023-10-20\r\nTXN_8501819,Juice,,3.0,6.0,Cash,,2023-03-30\r\nTXN_3068204,Cookie,1,1.0,1.0,Credit Card,Takeaway,2023-10-03\r\nTXN_8427104,Salad,2,ERROR,10.0,,In-store,2023-10-27\r\nTXN_8471743,ERROR,5,3.0,15.0,Digital Wallet,In-store,2023-04-06\r\nTXN_2621580,Tea,2,1.5,3.0,Cash,In-store,2023-03-22\r\nTXN_4726376,Cake,2,3.0,6.0,Credit Card,In-store,2023-01-31\r\nTXN_6044979,,1,1.0,1.0,Cash,In-store,2023-12-08\r\nTXN_4238417,Salad,2,5.0,10.0,,ERROR,2023-06-19\r\nTXN_1900620,Smoothie,2,4.0,8.0,Credit Card,ERROR,2023-12-14\r\nTXN_6420335,Coffee,1,2.0,2.0,Cash,Takeaway,2023-07-16\r\nTXN_3858209,Sandwich,4,4.0,16.0,Cash,,2023-02-22\r\nTXN_2091733,Salad,1,5.0,5.0,,In-store,\r\nTXN_8735480,Tea,5,1.5,7.5,Cash,,2023-06-02\r\nTXN_3829165,Juice,4,3.0,12.0,Cash,In-store,2023-06-15\r\nTXN_3748616,Coffee,2,2.0,4.0,Credit Card,In-store,2023-12-09\r\nTXN_1993289,Sandwich,2,4.0,8.0,,In-store,2023-04-18\r\nTXN_2123367,Cookie,2,1.0,2.0,,,2023-11-07\r\nTXN_5266394,Cake,3,3.0,9.0,Cash,In-store,2023-10-28\r\nTXN_5107946,Cake,4,3.0,12.0,Credit Card,,2023-12-22\r\nTXN_8035512,Tea,3,,4.5,Cash,UNKNOWN,2023-10-29\r\nTXN_8718498,Cake,5,3.0,15.0,Credit Card,ERROR,2023-04-30\r\nTXN_3955361,Cookie,5,1.0,5.0,,Takeaway,2023-04-02\r\nTXN_9487821,ERROR,1,5.0,5.0,Digital Wallet,Takeaway,2023-05-24\r\nTXN_4132730,,5,1.0,5.0,,In-store,2023-03-12\r\nTXN_8976658,Tea,2,1.5,3.0,Credit Card,In-store,2023-08-16\r\nTXN_5455936,UNKNOWN,5,3.0,15.0,,In-store,2023-10-28\r\nTXN_2725602,Juice,5,3.0,15.0,Credit Card,,2023-09-10\r\nTXN_3011323,Coffee,3,2.0,6.0,Credit Card,,2023-03-07\r\nTXN_6289610,Juice,3,3.0,UNKNOWN,Cash,Takeaway,2023-08-07\r\nTXN_8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20\r\nTXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10\r\nTXN_3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15\r\nTXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27\r\nTXN_8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25\r\nTXN_9517146,,5,5.0,25.0,Cash,Takeaway,2023-10-30\r\nTXN_1621920,Salad,3,5.0,15.0,,Takeaway,2023-10-28\r\nTXN_3808639,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-12-15\r\nTXN_7028009,Cake,4,3.0,12.0,,Takeaway,ERROR\r\nTXN_7447872,Juice,2,,6.0,,,\r\nTXN_6955416,Salad,4,5.0,20.0,ERROR,In-store,2023-02-25\r\nTXN_3775339,Cookie,3,1.0,3.0,Credit Card,UNKNOWN,2023-04-03\r\nTXN_9547091,Cookie,3,1.0,3.0,Credit Card,,2023-10-08\r\nTXN_4358673,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-12-28\r\nTXN_4174591,Tea,4,1.5,6.0,Digital Wallet,,2023-08-30\r\nTXN_3398520,Sandwich,1,4.0,4.0,,In-store,2023-02-03\r\nTXN_6171384,Smoothie,2,4.0,8.0,Credit Card,,2023-09-12\r\nTXN_2530938,Smoothie,5,4.0,20.0,,Takeaway,2023-04-27\r\nTXN_3314971,Juice,3,3.0,9.0,Digital Wallet,,2023-05-04\r\nTXN_3092382,Coffee,5,2.0,10.0,Digital Wallet,,2023-02-21\r\nTXN_1001832,Salad,2,5.0,10.0,Cash,Takeaway,UNKNOWN\r\nTXN_1535311,Juice,3,3.0,9.0,Cash,,2023-03-16\r\nTXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10\r\nTXN_4633784,ERROR,5,,15.0,,In-store,2023-02-06\r\nTXN_4368416,Salad,2,5.0,10.0,Credit Card,Takeaway,2023-02-24\r\nTXN_9790731,Cake,2,3.0,6.0,UNKNOWN,,2023-06-02\r\nTXN_9339456,Coffee,3,2.0,6.0,,Takeaway,2023-03-29\r\nTXN_5179020,Cake,2,3.0,6.0,,Takeaway,2023-06-18\r\nTXN_6258471,Coffee,5,2.0,10.0,Digital Wallet,In-store,2023-09-23\r\nTXN_7945375,Juice,3,3.0,9.0,,,2023-01-14\r\nTXN_4685453,Tea,4,1.5,6.0,Cash,In-store,2023-09-14\r\nTXN_9646452,Juice,5,3.0,15.0,Credit Card,,2023-09-16\r\nTXN_9096052,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-12-28\r\nTXN_5916991,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-02-06\r\nTXN_3407169,Sandwich,2,4.0,8.0,Cash,In-store,2023-03-11\r\nTXN_2277042,Tea,1,1.5,1.5,Cash,,2023-04-08\r\nTXN_9273729,Tea,1,1.5,1.5,,,2023-12-19\r\nTXN_2181545,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-07-14\r\nTXN_1150033,Juice,5,3.0,15.0,Cash,In-store,2023-04-18\r\nTXN_1443912,Juice,2,3.0,6.0,,,2023-06-08\r\nTXN_8700451,Tea,5,1.5,7.5,Credit Card,Takeaway,2023-12-12\r\nTXN_6380550,Coffee,5,2.0,10.0,Cash,In-store,2023-01-05\r\nTXN_4885518,Salad,3,5.0,15.0,Credit Card,In-store,2023-06-10\r\nTXN_3972167,Sandwich,5,4.0,20.0,,In-store,2023-01-23\r\nTXN_4878378,Tea,1,1.5,1.5,Credit Card,,2023-02-20\r\nTXN_2484241,Cake,3,UNKNOWN,9.0,Digital Wallet,,2023-07-19\r\nTXN_2368126,Cake,5,3.0,15.0,,In-store,2023-12-06\r\nTXN_7943008,Coffee,1,2.0,2.0,Credit Card,,ERROR\r\nTXN_8495063,Juice,1,3.0,UNKNOWN,Cash,,2023-05-31\r\nTXN_4811133,Salad,2,5.0,10.0,Cash,,2023-08-11\r\nTXN_8729570,Tea,5,1.5,7.5,UNKNOWN,In-store,2023-09-03\r\nTXN_7623634,Cake,2,3.0,,Credit Card,In-store,2023-07-11\r\nTXN_9336980,Salad,4,UNKNOWN,20.0,Cash,In-store,2023-06-06\r\nTXN_3424331,Cake,4,3.0,12.0,,,2023-01-18\r\nTXN_5072031,Cake,2,3.0,6.0,Cash,Takeaway,2023-03-23\r\nTXN_8687151,Salad,5,5.0,25.0,Cash,,2023-06-10\r\nTXN_4031509,,4,,16.0,Credit Card,Takeaway,2023-01-04\r\nTXN_5265095,Coffee,1,2.0,2.0,ERROR,,2023-06-23\r\nTXN_6541415,UNKNOWN,UNKNOWN,3.0,12.0,Cash,In-store,2023-11-25\r\nTXN_4108138,Coffee,5,2.0,10.0,Cash,,2023-08-03\r\nTXN_1909796,Smoothie,2,4.0,8.0,,Takeaway,2023-07-12\r\nTXN_1928241,Coffee,3,2.0,6.0,Cash,In-store,2023-04-30\r\nTXN_4283157,Salad,5,5.0,25.0,Digital Wallet,In-store,2023-11-25\r\nTXN_8013032,Coffee,2,2.0,4.0,Credit Card,,2023-03-07\r\nTXN_8301424,Juice,2,3.0,6.0,,ERROR,2023-06-27\r\nTXN_1093800,Sandwich,3,4.0,12.0,Cash,Takeaway,\r\nTXN_7965998,Juice,1,UNKNOWN,3.0,Credit Card,In-store,2023-11-02\r\nTXN_9238666,Cookie,1,UNKNOWN,1.0,ERROR,Takeaway,2023-07-31\r\nTXN_1631695,Tea,2,1.5,3.0,,In-store,2023-09-19\r\nTXN_1435086,Cake,5,,15.0,,ERROR,2023-02-09\r\nTXN_3226832,UNKNOWN,5,4.0,20.0,Cash,UNKNOWN,2023-09-04\r\nTXN_1648671,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-05-21\r\nTXN_4062737,Cake,3,3.0,9.0,Cash,In-store,2023-07-02\r\nTXN_3494565,,2,4.0,8.0,ERROR,,2023-07-10\r\nTXN_9249507,Cookie,4,1.0,4.0,Credit Card,In-store,2023-11-21\r\nTXN_4689500,Sandwich,4,4.0,16.0,,,2023-12-02\r\nTXN_8989148,Tea,2,1.5,,,,2023-11-25\r\nTXN_8316826,Coffee,3,2.0,6.0,,In-store,2023-04-17\r\nTXN_9836934,Cookie,3,1.0,3.0,Digital Wallet,In-store,2023-03-13\r\nTXN_8005489,Cake,3,3.0,9.0,,In-store,2023-08-12\r\nTXN_6463132,Cookie,5,1.0,5.0,Credit Card,Takeaway,\r\nTXN_3925836,Cookie,3,1.0,3.0,Digital Wallet,In-store,2023-02-16\r\nTXN_1896955,Salad,ERROR,5.0,25.0,,In-store,2023-09-23\r\nTXN_5075974,Smoothie,ERROR,4.0,16.0,Digital Wallet,,2023-04-11\r\nTXN_3978874,Smoothie,5,4.0,20.0,Credit Card,In-store,2023-03-13\r\nTXN_8955912,Sandwich,1,4.0,4.0,,,2023-11-07\r\nTXN_1136554,Smoothie,3,4.0,12.0,UNKNOWN,Takeaway,2023-03-26\r\nTXN_8007337,Cake,2,3.0,6.0,Digital Wallet,Takeaway,2023-11-01\r\nTXN_8129834,Salad,1,5.0,5.0,Cash,,2023-07-22\r\nTXN_3831848,UNKNOWN,1,4.0,4.0,Digital Wallet,Takeaway,2023-11-03\r\nTXN_5365809,Cake,3,3.0,9.0,Cash,In-store,2023-09-14\r\nTXN_8166407,Smoothie,2,,8.0,,,2023-07-26\r\nTXN_6629480,Smoothie,5,4.0,20.0,Credit Card,In-store,2023-02-28\r\nTXN_3833797,Coffee,4,2.0,8.0,UNKNOWN,In-store,2023-01-27\r\nTXN_2643815,Cookie,UNKNOWN,1.0,3.0,ERROR,,2023-12-06\r\nTXN_2996519,Cake,5,3.0,15.0,Cash,,2023-01-19\r\nTXN_8810894,Smoothie,1,4.0,4.0,,,2023-02-20\r\nTXN_7412722,Juice,4,3.0,12.0,Cash,In-store,2023-04-07\r\nTXN_3937509,Smoothie,2,4.0,8.0,,In-store,2023-03-20\r\nTXN_6000201,Cookie,3,1.0,3.0,Cash,Takeaway,2023-02-16\r\nTXN_1714274,Cookie,4,1.0,4.0,,In-store,2023-12-27\r\nTXN_3800182,Tea,2,ERROR,3.0,Cash,In-store,2023-10-26\r\nTXN_5115080,,5,3.0,15.0,Credit Card,,2023-02-18\r\nTXN_9788956,Juice,ERROR,3.0,12.0,ERROR,,2023-04-11\r\nTXN_6311602,Juice,3,3.0,9.0,Credit Card,,2023-05-15\r\nTXN_2950680,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-12-10\r\nTXN_6749847,Cake,2,3.0,6.0,Credit Card,,2023-08-15\r\nTXN_2143187,Smoothie,1,4.0,4.0,,In-store,2023-04-21\r\nTXN_8964522,,3,3.0,9.0,Credit Card,Takeaway,2023-10-28\r\nTXN_4088917,Coffee,3,2.0,6.0,Cash,Takeaway,2023-02-04\r\nTXN_3779366,Cookie,1,1.0,1.0,Digital Wallet,In-store,2023-04-15\r\nTXN_7724048,Smoothie,1,4.0,4.0,ERROR,In-store,2023-11-12\r\nTXN_2698591,Tea,5,1.5,7.5,,,2023-08-05\r\nTXN_3171373,Smoothie,3,4.0,12.0,Credit Card,In-store,2023-05-10\r\nTXN_4129248,Sandwich,2,4.0,8.0,Credit Card,,ERROR\r\nTXN_6498163,Smoothie,5,4.0,20.0,,In-store,2023-07-15\r\nTXN_6717827,ERROR,3,5.0,15.0,Digital Wallet,,2023-11-15\r\nTXN_9089898,Salad,3,ERROR,15.0,Credit Card,,2023-01-11\r\nTXN_8587583,Cake,1,ERROR,3.0,,,2023-10-01\r\nTXN_8693704,Salad,ERROR,5.0,25.0,Cash,In-store,2023-05-04\r\nTXN_3857960,Salad,4,5.0,20.0,Cash,In-store,2023-04-26\r\nTXN_3499124,ERROR,4,4.0,16.0,Credit Card,,2023-08-25\r\nTXN_9250710,Salad,1,5.0,5.0,Cash,In-store,2023-05-28\r\nTXN_7058377,Juice,1,3.0,3.0,,Takeaway,2023-04-30\r\nTXN_6766492,Salad,1,5.0,5.0,,ERROR,2023-01-14\r\nTXN_9879996,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-03-01\r\nTXN_4291940,Cake,3,3.0,9.0,Credit Card,In-store,2023-11-13\r\nTXN_7433461,Cookie,2,1.0,2.0,Digital Wallet,,2023-07-09\r\nTXN_4068262,Salad,2,5.0,10.0,Credit Card,,2023-05-13\r\nTXN_5761073,Cookie,1,1.0,1.0,Cash,In-store,UNKNOWN\r\nTXN_5047447,Salad,1,5.0,5.0,Digital Wallet,Takeaway,2023-12-27\r\nTXN_6623508,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-05-18\r\nTXN_2651216,UNKNOWN,3,4.0,12.0,,,2023-04-04\r\nTXN_9350833,Cake,1,UNKNOWN,3.0,Cash,Takeaway,2023-01-17\r\nTXN_8377564,Cake,5,3.0,15.0,,In-store,2023-07-14\r\nTXN_7031118,Salad,1,5.0,5.0,Credit Card,ERROR,2023-03-29\r\nTXN_2230167,Cake,4,3.0,12.0,Digital Wallet,Takeaway,2023-09-22\r\nTXN_6446616,Tea,3,1.5,4.5,ERROR,,2023-09-30\r\nTXN_1721827,Cake,4,3.0,12.0,Digital Wallet,ERROR,2023-08-22\r\nTXN_6334895,Smoothie,1,4.0,4.0,Credit Card,ERROR,2023-07-27\r\nTXN_7077119,ERROR,1,4.0,4.0,Digital Wallet,In-store,2023-12-30\r\nTXN_8562645,Salad,ERROR,5.0,UNKNOWN,,In-store,2023-05-18\r\nTXN_4700144,Coffee,4,2.0,8.0,,In-store,2023-12-21\r\nTXN_5526852,Sandwich,5,4.0,,Digital Wallet,In-store,2023-09-28\r\nTXN_6846228,Salad,3,,15.0,,In-store,2023-11-16\r\nTXN_8570890,Juice,4,3.0,12.0,,,2023-04-14\r\nTXN_3205009,ERROR,2,1.5,3.0,Cash,In-store,2023-01-03\r\nTXN_3786188,Tea,3,1.5,4.5,Credit Card,In-store,2023-10-20\r\nTXN_4530804,Coffee,4,2.0,8.0,,,2023-01-12\r\nTXN_9642066,Sandwich,3,4.0,12.0,Credit Card,In-store,2023-08-31\r\nTXN_7328294,Juice,2,3.0,6.0,Cash,,2023-07-07\r\nTXN_1908636,Tea,2,1.5,3.0,,UNKNOWN,\r\nTXN_9238066,,5,1.5,7.5,Digital Wallet,In-store,2023-09-15\r\nTXN_5415901,Cake,2,3.0,6.0,Digital Wallet,,2023-10-21\r\nTXN_6714420,ERROR,2,3.0,6.0,Credit Card,Takeaway,2023-03-30\r\nTXN_6616971,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-09-02\r\nTXN_7803615,Salad,3,5.0,15.0,Cash,In-store,2023-12-13\r\nTXN_7549542,Cookie,5,1.0,5.0,,Takeaway,\r\nTXN_3544789,Tea,4,1.5,ERROR,UNKNOWN,In-store,2023-07-14\r\nTXN_1583597,Salad,1,5.0,5.0,Cash,In-store,2023-05-10\r\nTXN_8472308,Cookie,2,1.0,2.0,Digital Wallet,Takeaway,2023-08-19\r\nTXN_1967565,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-03-31\r\nTXN_2029497,Sandwich,2,4.0,8.0,Cash,Takeaway,2023-01-06\r\nTXN_8929774,ERROR,3,3.0,9.0,Cash,,2023-10-02\r\nTXN_5003018,Cookie,4,1.0,UNKNOWN,Digital Wallet,,UNKNOWN\r\nTXN_7852990,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-07-10\r\nTXN_2534066,Salad,2,5.0,10.0,Cash,,2023-10-13\r\nTXN_2059647,Tea,1,1.5,1.5,Digital Wallet,In-store,2023-05-29\r\nTXN_2485183,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-07\r\nTXN_7374846,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-29\r\nTXN_9401522,Sandwich,4,4.0,16.0,Digital Wallet,In-store,2023-11-16\r\nTXN_8250651,Sandwich,4,4.0,16.0,Digital Wallet,In-store,2023-03-13\r\nTXN_7191245,Cake,4,3.0,12.0,,Takeaway,2023-05-22\r\nTXN_8982764,Cake,5,3.0,15.0,Digital Wallet,Takeaway,2023-11-23\r\nTXN_8669422,,4,3.0,12.0,Cash,Takeaway,2023-10-15\r\nTXN_1153869,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-11-03\r\nTXN_5043774,Sandwich,3,4.0,12.0,Cash,,2023-06-08\r\nTXN_1746320,Salad,1,5.0,5.0,Cash,,2023-11-14\r\nTXN_1077129,Cookie,1,1.0,1.0,,In-store,2023-09-12\r\nTXN_4865338,Sandwich,UNKNOWN,4.0,16.0,,In-store,2023-11-26\r\nTXN_5616583,Smoothie,1,4.0,4.0,,,2023-10-13\r\nTXN_2078474,Cookie,2,1.0,2.0,,Takeaway,2023-11-03\r\nTXN_2130245,Smoothie,5,4.0,20.0,Credit Card,,2023-11-13\r\nTXN_3229409,Juice,UNKNOWN,3.0,UNKNOWN,Cash,Takeaway,2023-04-15\r\nTXN_9076216,Cake,1,3.0,3.0,Cash,,2023-12-17\r\nTXN_6371987,Tea,5,1.5,ERROR,UNKNOWN,Takeaway,2023-03-13\r\nTXN_9913877,ERROR,2,2.0,4.0,Credit Card,,2023-05-09\r\nTXN_2084377,Smoothie,1,4.0,4.0,Credit Card,ERROR,2023-10-22\r\nTXN_1842675,ERROR,4,1.0,4.0,Credit Card,Takeaway,2023-06-23\r\nTXN_8605813,Cookie,1,1.0,1.0,,,2023-06-30\r\nTXN_9755352,Sandwich,5,4.0,20.0,,In-store,2023-05-13\r\nTXN_7550498,Juice,5,3.0,15.0,,In-store,ERROR\r\nTXN_2305908,Coffee,UNKNOWN,2.0,8.0,Cash,,2023-04-25\r\nTXN_6953697,UNKNOWN,3,4.0,12.0,,Takeaway,2023-05-27\r\nTXN_3495950,,4,ERROR,6.0,Credit Card,In-store,2023-02-19\r\nTXN_7557340,Tea,5,1.5,7.5,Credit Card,In-store,2023-12-11\r\nTXN_1157817,Smoothie,1,4.0,4.0,Digital Wallet,In-store,2023-04-25\r\nTXN_2020318,Tea,3,1.5,4.5,Digital Wallet,In-store,2023-10-12\r\nTXN_8692094,Coffee,5,2.0,10.0,,Takeaway,2023-08-30\r\nTXN_5307411,Cake,3,3.0,ERROR,Digital Wallet,Takeaway,2023-10-21\r\nTXN_9703120,Coffee,3,2.0,6.0,Credit Card,,2023-11-02\r\nTXN_1289133,Juice,1,3.0,3.0,Cash,UNKNOWN,2023-09-19\r\nTXN_2031459,Cake,3,3.0,9.0,Cash,Takeaway,2023-07-04\r\nTXN_1333682,Smoothie,1,4.0,4.0,Digital Wallet,,2023-01-28\r\nTXN_2256622,Cookie,2,,2.0,Cash,In-store,2023-10-04\r\nTXN_1623966,Tea,2,1.5,3.0,Cash,Takeaway,UNKNOWN\r\nTXN_4912930,Smoothie,3,4.0,12.0,Credit Card,In-store,2023-02-26\r\nTXN_4942692,Coffee,2,2.0,4.0,,Takeaway,2023-01-15\r\nTXN_3723007,Tea,3,1.5,4.5,Digital Wallet,In-store,2023-05-18\r\nTXN_7922392,Sandwich,3,4.0,12.0,,,2023-05-03\r\nTXN_7498727,Salad,3,5.0,15.0,Cash,,2023-11-06\r\nTXN_1222338,Cookie,1,1.0,1.0,,In-store,2023-10-11\r\nTXN_6878866,Smoothie,3,4.0,12.0,Credit Card,,2023-02-25\r\nTXN_1260335,Cookie,4,1.0,4.0,Digital Wallet,In-store,\r\nTXN_9223242,Smoothie,2,4.0,8.0,,,2023-09-10\r\nTXN_6244211,Smoothie,2,4.0,8.0,,,2023-08-11\r\nTXN_5446858,,1,1.0,1.0,Cash,In-store,2023-11-07\r\nTXN_4612864,Tea,3,1.5,4.5,,,2023-02-14\r\nTXN_5411381,Cookie,ERROR,1.0,1.0,,,2023-04-28\r\nTXN_3047598,Cookie,1,1.0,1.0,,,2023-09-06\r\nTXN_5754317,Coffee,2,,4.0,Credit Card,Takeaway,2023-01-10\r\nTXN_7496926,Sandwich,3,4.0,12.0,ERROR,In-store,2023-04-23\r\nTXN_1726858,Smoothie,3,4.0,12.0,Cash,In-store,\r\nTXN_7559388,Salad,4,5.0,20.0,Digital Wallet,Takeaway,2023-02-26\r\nTXN_8540499,Cookie,3,1.0,3.0,Cash,In-store,2023-01-22\r\nTXN_4225756,Cookie,3,1.0,3.0,,In-store,2023-03-10\r\nTXN_6795640,Cookie,4,1.0,4.0,Digital Wallet,Takeaway,2023-01-28\r\nTXN_6702428,Coffee,5,2.0,10.0,Cash,Takeaway,2023-08-11\r\nTXN_8955259,ERROR,2,4.0,8.0,Credit Card,,2023-11-18\r\nTXN_4639319,Coffee,5,2.0,10.0,Cash,,2023-01-09\r\nTXN_5997803,Coffee,5,2.0,10.0,,In-store,2023-12-03\r\nTXN_1340956,ERROR,4,2.0,8.0,,,2023-10-26\r\nTXN_1259671,Sandwich,UNKNOWN,4.0,12.0,Digital Wallet,In-store,2023-10-08\r\nTXN_8319993,Juice,1,3.0,3.0,Digital Wallet,,2023-08-06\r\nTXN_8894157,Sandwich,4,4.0,16.0,Credit Card,,ERROR\r\nTXN_5523450,Salad,5,5.0,25.0,Credit Card,Takeaway,2023-07-02\r\nTXN_7838964,Sandwich,3,4.0,12.0,Credit Card,In-store,2023-06-15\r\nTXN_2773987,Smoothie,5,4.0,20.0,ERROR,,2023-01-11\r\nTXN_1158829,Tea,1,UNKNOWN,1.5,Credit Card,,2023-10-02\r\nTXN_2523298,,4,,6.0,ERROR,In-store,2023-03-25\r\nTXN_8685737,Smoothie,2,4.0,8.0,,In-store,2023-11-02\r\nTXN_5634135,Cookie,2,UNKNOWN,2.0,,ERROR,2023-01-27\r\nTXN_1524626,Smoothie,2,4.0,8.0,Digital Wallet,,2023-12-29\r\nTXN_7275407,Smoothie,2,4.0,8.0,Digital Wallet,In-store,2023-10-20\r\nTXN_2889622,Juice,4,3.0,12.0,Credit Card,,2023-11-01\r\nTXN_6849113,Cookie,ERROR,1.0,1.0,Credit Card,,2023-07-14\r\nTXN_2265316,Cookie,,1.0,3.0,Credit Card,In-store,2023-12-29\r\nTXN_9472241,Salad,3,5.0,15.0,Cash,Takeaway,2023-06-30\r\nTXN_7345414,Salad,1,,5.0,,UNKNOWN,2023-02-15\r\nTXN_4473352,Cake,1,3.0,3.0,UNKNOWN,In-store,2023-11-16\r\nTXN_2814363,Tea,2,1.5,3.0,,,2023-07-02\r\nTXN_1846004,Juice,3,3.0,9.0,Cash,In-store,2023-05-21\r\nTXN_7140471,Cake,1,3.0,3.0,Credit Card,,2023-05-25\r\nTXN_3119542,Smoothie,1,4.0,4.0,Credit Card,,2023-10-31\r\nTXN_7773968,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-02-24\r\nTXN_9081088,Tea,2,1.5,3.0,Cash,Takeaway,2023-02-27\r\nTXN_8559167,Sandwich,5,4.

In [ ]:
import pandas as pd
import numpy as np
#Load CSV
df=pd.read_csv("/content/dirty_cafe_sales.csv")

print(df.head())
print(df.info())

  Transaction ID    Item Quantity Price Per Unit Total Spent  Payment Method  \
0    TXN_1961373  Coffee        2            2.0         4.0     Credit Card
1    TXN_4977031    Cake        4            3.0        12.0            Cash
2    TXN_4271903  Cookie        4            1.0       ERROR     Credit Card
3    TXN_7034554   Salad        2            5.0        10.0         UNKNOWN
4    TXN_3160411  Coffee        2            2.0         4.0  Digital Wallet

   Location Transaction Date
0  Takeaway       2023-09-08
1  In-store       2023-05-16
2  In-store       2023-07-19
3   UNKNOWN       2023-04-27
4  In-store       2023-06-11
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB
None

In [ ]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

Creating a series of pandas

In [ ]:
s = pd.Series([10,20,30])

DataFrame[ task1: create a pandas dataframe with 5 column]

In [ ]:
df1 = pd.DataFrame({
    "class 1": [85,90,75,98,95],
    "class 2": [65,78,98,88,99],
    "class 3":[80,85,67,88,99],
    "class 4":[45,67,88,97,94],
    "class 5":[87,86,95,96,97]
})

In [ ]:
df1

   class 1  class 2  class 3  class 4  class 5
0       85       65       80       45       87
1       90       78       85       67       86
2       75       98       67       88       95
3       98       88       88       97       96
4       95       99       99       94       97

In [ ]:
df=pd.DataFrame({
    "age":[21,22,26,24,25],
    "salary":[30000,40000,50000,10000000,550000000],
})

In [ ]:
df

   age     salary
0   21      30000
1   22      40000
2   26      50000
3   24   10000000
4   25  550000000

Column Selection

In [ ]:
df["age"]

0    21
1    22
2    26
3    24
4    25
Name: age, dtype: int64

In [ ]:
df[["age","salary"]]

   age     salary
0   21      30000
1   22      40000
2   26      50000
3   24   10000000
4   25  550000000

Row Filtering

In [ ]:
df[df["age"]>25]

   age  salary
2   26   50000

In [ ]:
1+0

1

In [ ]:
df[(df["age"]>20) & (df["salary"]<50000)]

   age  salary
0   21   30000
1   22   40000

In [ ]:
df[(df["age"]>20) | (df["salary"]<50000)]

   age     salary
0   21      30000
1   22      40000
2   26      50000
3   24   10000000
4   25  550000000

Insert columns

In [ ]:
df["experience"]= [1,3,5,4,6]

In [ ]:
df

   age     salary  experience
0   21      30000           1
1   22      40000           3
2   26      50000           5
3   24   10000000           4
4   25  550000000           6

In [ ]:
df.dtypes

age           int64
salary        int64
experience    int64
dtype: object

In [ ]:
df["awards"]=[1,3,4,2,None]

In [ ]:
df

   age     salary  experience  awards
0   21      30000           1     1.0
1   22      40000           3     3.0
2   26      50000           5     4.0
3   24   10000000           4     2.0
4   25  550000000           6     NaN

In [ ]:
#broadcasting

df["country"]="Nepal"

In [ ]:
df

   age     salary  experience  awards country
0   21      30000           1     1.0   Nepal
1   22      40000           3     3.0   Nepal
2   26      50000           5     4.0   Nepal
3   24   10000000           4     2.0   Nepal
4   25  550000000           6     NaN   Nepal

Inserting columns with missing values

In [ ]:
import numpy as np

In [ ]:
df["bonus"]=[5000,np.nan,70000,np.nan,np.nan]

In [ ]:
df.head(2)
df.tail()

   age     salary  experience  awards country    bonus
0   21      30000           1     1.0   Nepal   5000.0
1   22      40000           3     3.0   Nepal      NaN
2   26      50000           5     4.0   Nepal  70000.0
3   24   10000000           4     2.0   Nepal      NaN
4   25  550000000           6     NaN   Nepal      NaN

In [ ]:
df.tail()

   age     salary  experience  awards country    bonus
0   21      30000           1     1.0   Nepal   5000.0
1   22      40000           3     3.0   Nepal      NaN
2   26      50000           5     4.0   Nepal  70000.0
3   24   10000000           4     2.0   Nepal      NaN
4   25  550000000           6     NaN   Nepal      NaN

In [ ]:
df1.tail()

   class 1  class 2  class 3  class 4  class 5
0       85       65       80       45       87
1       90       78       85       67       86
2       75       98       67       88       95
3       98       88       88       97       96
4       95       99       99       94       97

Inserting rows

len(df) gives the next available index

.loc[] assigns values row-wise

In [ ]:
df.loc[len(df)] = [35,60000,3,2,'Nepal',300]

In [ ]:
df

   age     salary  experience  awards country    bonus
0   21      30000           1     1.0   Nepal   5000.0
1   22      40000           3     3.0   Nepal      NaN
2   26      50000           5     4.0   Nepal  70000.0
3   24   10000000           4     2.0   Nepal      NaN
4   25  550000000           6     NaN   Nepal      NaN
5   35      60000           3     2.0   Nepal    300.0

Adding & Modifying Columns

In [ ]:
df["age_squared"]=df["age"]*2

In [ ]:
df

,age,monthly_salary,experience,awards,country,bonus,age_squared,salary_k
0,21,30000,1,1.0,Nepal,3000.0,42,30.0
1,22,40000,3,3.0,Nepal,4000.0,44,40.0
2,26,50000,5,4.0,Nepal,5000.0,52,50.0
3,24,10000000,4,2.0,Nepal,1000000.0,48,10000.0
4,25,550000000,6,NaN,Nepal,55000000.0,50,550000.0
5,35,60000,3,2.0,Nepal,6000.0,70,60.0

In [ ]:
df["bonus2"]=df["salary"]*0.01

In [ ]:
df["salary_k"]=df["salary"]/1000

In [ ]:
df["bonus"]=df["salary"]*0.10

Rename Columns

In [ ]:
df.rename(columns={"salary": "monthly_salary"},inplace=True)

In [ ]:
df

,age,monthly_salary,experience,awards,country,bonus,salary_k,age_squared
0,21,30000,1,1.0,Nepal,3000.0,30.0,42
1,22,40000,3,3.0,Nepal,4000.0,40.0,44
2,26,50000,5,4.0,Nepal,5000.0,50.0,52
3,24,10000000,4,2.0,Nepal,1000000.0,10000.0,48
4,25,550000000,6,NaN,Nepal,55000000.0,550000.0,50
5,35,60000,3,2.0,Nepal,6000.0,60.0,70

In [ ]:
df.drop(['age_squared'], axis=1, inplace=True)

In [ ]:
df

   age  monthly_salary  experience  awards country       bonus  salary_k
0   21           30000           1     1.0   Nepal      3000.0      30.0
1   22           40000           3     3.0   Nepal      4000.0      40.0
2   26           50000           5     4.0   Nepal      5000.0      50.0
3   24        10000000           4     2.0   Nepal   1000000.0   10000.0
4   25       550000000           6     NaN   Nepal  55000000.0  550000.0
5   35           60000           3     2.0   Nepal      6000.0      60.0

In [ ]:
df.drop(['awards', 'country'], axis=1, inplace=True)

In [ ]:
df

   age  monthly_salary  experience       bonus  salary_k
0   21           30000           1      3000.0      30.0
1   22           40000           3      4000.0      40.0
2   26           50000           5      5000.0      50.0
3   24        10000000           4   1000000.0   10000.0
4   25       550000000           6  55000000.0  550000.0
5   35           60000           3      6000.0      60.0


Change Data Types

In [ ]:
df["monthly_salary"] = df["monthly_salary"].astype(float)

In [ ]:
df.dtypes

age                 int64
monthly_salary    float64
experience          int64
bonus             float64
salary_k          float64
dtype: object

In [ ]:
df

   age  monthly_salary  experience       bonus  salary_k
0   21         30000.0           1      3000.0      30.0
1   22         40000.0           3      4000.0      40.0
2   26         50000.0           5      5000.0      50.0
3   24      10000000.0           4   1000000.0   10000.0
4   25     550000000.0           6  55000000.0  550000.0
5   35         60000.0           3      6000.0      60.0

Reading Data

In [ ]:
from google.colab import files
files.upload()

Saving dirty_cafe_sales.csv to dirty_cafe_sales.csv

{'dirty_cafe_sales.csv': b'Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date\r\nTXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08\r\nTXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16\r\nTXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19\r\nTXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27\r\nTXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11\r\nTXN_2602893,Smoothie,5,4.0,20.0,Credit Card,,2023-03-31\r\nTXN_4433211,UNKNOWN,3,3.0,9.0,ERROR,Takeaway,2023-10-06\r\nTXN_6699534,Sandwich,4,4.0,16.0,Cash,UNKNOWN,2023-10-28\r\nTXN_4717867,,5,3.0,15.0,,Takeaway,2023-07-28\r\nTXN_2064365,Sandwich,5,4.0,20.0,,In-store,2023-12-31\r\nTXN_2548360,Salad,5,5.0,25.0,Cash,Takeaway,2023-11-07\r\nTXN_3051279,Sandwich,2,4.0,8.0,Credit Card,Takeaway,ERROR\r\nTXN_7619095,Sandwich,2,4.0,8.0,Cash,In-store,2023-05-03\r\nTXN_9437049,Cookie,5,1.0,5.0,,Takeaway,2023-06-01\r\nTXN_8915701,ERROR,2,1.5,3.0,,In-store,2023-03-21\r\nTXN_2847255,Salad,3,5.0,15.0,Credit Card,In-store,2023-11-15\r\nTXN_3765707,Sandwich,1,4.0,4.0,,,2023-06-10\r\nTXN_6769710,Juice,2,3.0,6.0,Cash,In-store,2023-02-24\r\nTXN_8876618,Cake,5,3.0,15.0,Cash,ERROR,2023-03-25\r\nTXN_3709394,Juice,4,3.0,12.0,Cash,Takeaway,2023-01-15\r\nTXN_3522028,Smoothie,ERROR,4.0,20.0,Cash,In-store,2023-04-04\r\nTXN_3567645,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-03-30\r\nTXN_5132361,Sandwich,3,4.0,12.0,Digital Wallet,Takeaway,2023-12-01\r\nTXN_2616390,Sandwich,2,4.0,8.0,,,2023-09-18\r\nTXN_9400181,Sandwich,5,4.0,20.0,Cash,In-store,2023-06-03\r\nTXN_7958992,Smoothie,3,4.0,,UNKNOWN,UNKNOWN,2023-12-13\r\nTXN_5183041,Cookie,5,1.0,5.0,Credit Card,In-store,2023-04-20\r\nTXN_5695074,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-04-10\r\nTXN_8467949,Smoothie,5,4.0,20.0,Credit Card,,2023-03-11\r\nTXN_7640952,Cake,4,3.0,12.0,Digital Wallet,Takeaway,ERROR\r\nTXN_1736287,,5,2.0,10.0,Digital Wallet,,2023-06-02\r\nTXN_8927252,UNKNOWN,2,1.0,ERROR,Credit Card,ERROR,2023-11-06\r\nTXN_9677376,Smoothie,4,4.0,16.0,,In-store,2023-08-15\r\nTXN_7710508,UNKNOWN,5,1.0,5.0,Cash,,ERROR\r\nTXN_8853997,Smoothie,2,4.0,8.0,Digital Wallet,Takeaway,2023-10-09\r\nTXN_9130559,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-28\r\nTXN_6855453,UNKNOWN,4,3.0,12.0,,In-store,2023-07-17\r\nTXN_1080432,Salad,2,5.0,10.0,Credit Card,In-store,2023-04-29\r\nTXN_2655815,Smoothie,4,4.0,16.0,,Takeaway,2023-06-08\r\nTXN_6688524,Coffee,4,2.0,8.0,ERROR,,2023-06-29\r\nTXN_2083138,Smoothie,3,4.0,12.0,,In-store,2023-04-17\r\nTXN_2427584,Sandwich,4,4.0,16.0,,Takeaway,2023-12-22\r\nTXN_6650263,Tea,2,1.5,UNKNOWN,,Takeaway,2023-01-10\r\nTXN_9620080,Juice,4,3.0,12.0,,Takeaway,2023-10-02\r\nTXN_1491578,Cookie,2,1.0,2.0,,,2023-02-23\r\nTXN_5455792,Salad,3,5.0,15.0,Cash,,2023-03-22\r\nTXN_8078640,Juice,4,3.0,12.0,Digital Wallet,In-store,2023-11-03\r\nTXN_9499313,Juice,5,3.0,15.0,,,2023-03-02\r\nTXN_8201146,Juice,5,3.0,15.0,Cash,,2023-06-26\r\nTXN_8230936,Cake,3,3.0,9.0,,ERROR,2023-05-02\r\nTXN_7742742,Cake,5,3.0,15.0,,Takeaway,2023-09-05\r\nTXN_6342161,Salad,5,5.0,25.0,ERROR,Takeaway,2023-01-08\r\nTXN_8914892,UNKNOWN,5,5.0,25.0,Digital Wallet,,2023-03-15\r\nTXN_3363746,Smoothie,3,4.0,12.0,Credit Card,,2023-11-25\r\nTXN_8614868,Smoothie,5,4.0,20.0,Digital Wallet,Takeaway,2023-12-05\r\nTXN_5522862,Cookie,ERROR,1.0,2.0,Credit Card,Takeaway,2023-03-19\r\nTXN_3578141,Cake,5,,15.0,,Takeaway,2023-06-27\r\nTXN_2080895,Cake,UNKNOWN,3.0,3.0,Digital Wallet,In-store,2023-04-19\r\nTXN_6421134,Sandwich,4,4.0,16.0,Cash,Takeaway,2023-11-03\r\nTXN_8813311,Juice,5,3.0,15.0,,In-store,2023-10-07\r\nTXN_9023317,Salad,1,5.0,5.0,,,2023-09-30\r\nTXN_8051289,,1,3.0,3.0,,In-store,2023-10-09\r\nTXN_2537617,Sandwich,1,4.0,4.0,Cash,,2023-05-27\r\nTXN_9099694,UNKNOWN,3,5.0,15.0,,Takeaway,2023-11-18\r\nTXN_9230615,Smoothie,4,4.0,16.0,Digital Wallet,,2023-06-01\r\nTXN_4987129,Sandwich,3,,,,In-store,2023-10-20\r\nTXN_8501819,Juice,,3.0,6.0,Cash,,2023-03-30\r\nTXN_3068204,Cookie,1,1.0,1.0,Credit Card,Takeaway,2023-10-03\r\nTXN_8427104,Salad,2,ERROR,10.0,,In-store,2023-10-27\r\nTXN_8471743,ERROR,5,3.0,15.0,Digital Wallet,In-store,2023-04-06\r\nTXN_2621580,Tea,2,1.5,3.0,Cash,In-store,2023-03-22\r\nTXN_4726376,Cake,2,3.0,6.0,Credit Card,In-store,2023-01-31\r\nTXN_6044979,,1,1.0,1.0,Cash,In-store,2023-12-08\r\nTXN_4238417,Salad,2,5.0,10.0,,ERROR,2023-06-19\r\nTXN_1900620,Smoothie,2,4.0,8.0,Credit Card,ERROR,2023-12-14\r\nTXN_6420335,Coffee,1,2.0,2.0,Cash,Takeaway,2023-07-16\r\nTXN_3858209,Sandwich,4,4.0,16.0,Cash,,2023-02-22\r\nTXN_2091733,Salad,1,5.0,5.0,,In-store,\r\nTXN_8735480,Tea,5,1.5,7.5,Cash,,2023-06-02\r\nTXN_3829165,Juice,4,3.0,12.0,Cash,In-store,2023-06-15\r\nTXN_3748616,Coffee,2,2.0,4.0,Credit Card,In-store,2023-12-09\r\nTXN_1993289,Sandwich,2,4.0,8.0,,In-store,2023-04-18\r\nTXN_2123367,Cookie,2,1.0,2.0,,,2023-11-07\r\nTXN_5266394,Cake,3,3.0,9.0,Cash,In-store,2023-10-28\r\nTXN_5107946,Cake,4,3.0,12.0,Credit Card,,2023-12-22\r\nTXN_8035512,Tea,3,,4.5,Cash,UNKNOWN,2023-10-29\r\nTXN_8718498,Cake,5,3.0,15.0,Credit Card,ERROR,2023-04-30\r\nTXN_3955361,Cookie,5,1.0,5.0,,Takeaway,2023-04-02\r\nTXN_9487821,ERROR,1,5.0,5.0,Digital Wallet,Takeaway,2023-05-24\r\nTXN_4132730,,5,1.0,5.0,,In-store,2023-03-12\r\nTXN_8976658,Tea,2,1.5,3.0,Credit Card,In-store,2023-08-16\r\nTXN_5455936,UNKNOWN,5,3.0,15.0,,In-store,2023-10-28\r\nTXN_2725602,Juice,5,3.0,15.0,Credit Card,,2023-09-10\r\nTXN_3011323,Coffee,3,2.0,6.0,Credit Card,,2023-03-07\r\nTXN_6289610,Juice,3,3.0,UNKNOWN,Cash,Takeaway,2023-08-07\r\nTXN_8268061,Salad,3,5.0,15.0,ERROR,Takeaway,2023-08-20\r\nTXN_5220895,Salad,5,5.0,25.0,Cash,In-store,2023-06-10\r\nTXN_3085509,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-04-15\r\nTXN_9999113,Juice,4,3.0,12.0,Cash,Takeaway,2023-05-27\r\nTXN_8779771,Coffee,4,2.0,8.0,Cash,In-store,2023-07-25\r\nTXN_9517146,,5,5.0,25.0,Cash,Takeaway,2023-10-30\r\nTXN_1621920,Salad,3,5.0,15.0,,Takeaway,2023-10-28\r\nTXN_3808639,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-12-15\r\nTXN_7028009,Cake,4,3.0,12.0,,Takeaway,ERROR\r\nTXN_7447872,Juice,2,,6.0,,,\r\nTXN_6955416,Salad,4,5.0,20.0,ERROR,In-store,2023-02-25\r\nTXN_3775339,Cookie,3,1.0,3.0,Credit Card,UNKNOWN,2023-04-03\r\nTXN_9547091,Cookie,3,1.0,3.0,Credit Card,,2023-10-08\r\nTXN_4358673,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-12-28\r\nTXN_4174591,Tea,4,1.5,6.0,Digital Wallet,,2023-08-30\r\nTXN_3398520,Sandwich,1,4.0,4.0,,In-store,2023-02-03\r\nTXN_6171384,Smoothie,2,4.0,8.0,Credit Card,,2023-09-12\r\nTXN_2530938,Smoothie,5,4.0,20.0,,Takeaway,2023-04-27\r\nTXN_3314971,Juice,3,3.0,9.0,Digital Wallet,,2023-05-04\r\nTXN_3092382,Coffee,5,2.0,10.0,Digital Wallet,,2023-02-21\r\nTXN_1001832,Salad,2,5.0,10.0,Cash,Takeaway,UNKNOWN\r\nTXN_1535311,Juice,3,3.0,9.0,Cash,,2023-03-16\r\nTXN_2148617,Juice,ERROR,3.0,9.0,Digital Wallet,UNKNOWN,2023-01-10\r\nTXN_4633784,ERROR,5,,15.0,,In-store,2023-02-06\r\nTXN_4368416,Salad,2,5.0,10.0,Credit Card,Takeaway,2023-02-24\r\nTXN_9790731,Cake,2,3.0,6.0,UNKNOWN,,2023-06-02\r\nTXN_9339456,Coffee,3,2.0,6.0,,Takeaway,2023-03-29\r\nTXN_5179020,Cake,2,3.0,6.0,,Takeaway,2023-06-18\r\nTXN_6258471,Coffee,5,2.0,10.0,Digital Wallet,In-store,2023-09-23\r\nTXN_7945375,Juice,3,3.0,9.0,,,2023-01-14\r\nTXN_4685453,Tea,4,1.5,6.0,Cash,In-store,2023-09-14\r\nTXN_9646452,Juice,5,3.0,15.0,Credit Card,,2023-09-16\r\nTXN_9096052,Smoothie,4,4.0,16.0,Credit Card,Takeaway,2023-12-28\r\nTXN_5916991,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-02-06\r\nTXN_3407169,Sandwich,2,4.0,8.0,Cash,In-store,2023-03-11\r\nTXN_2277042,Tea,1,1.5,1.5,Cash,,2023-04-08\r\nTXN_9273729,Tea,1,1.5,1.5,,,2023-12-19\r\nTXN_2181545,Juice,4,3.0,12.0,Credit Card,Takeaway,2023-07-14\r\nTXN_1150033,Juice,5,3.0,15.0,Cash,In-store,2023-04-18\r\nTXN_1443912,Juice,2,3.0,6.0,,,2023-06-08\r\nTXN_8700451,Tea,5,1.5,7.5,Credit Card,Takeaway,2023-12-12\r\nTXN_6380550,Coffee,5,2.0,10.0,Cash,In-store,2023-01-05\r\nTXN_4885518,Salad,3,5.0,15.0,Credit Card,In-store,2023-06-10\r\nTXN_3972167,Sandwich,5,4.0,20.0,,In-store,2023-01-23\r\nTXN_4878378,Tea,1,1.5,1.5,Credit Card,,2023-02-20\r\nTXN_2484241,Cake,3,UNKNOWN,9.0,Digital Wallet,,2023-07-19\r\nTXN_2368126,Cake,5,3.0,15.0,,In-store,2023-12-06\r\nTXN_7943008,Coffee,1,2.0,2.0,Credit Card,,ERROR\r\nTXN_8495063,Juice,1,3.0,UNKNOWN,Cash,,2023-05-31\r\nTXN_4811133,Salad,2,5.0,10.0,Cash,,2023-08-11\r\nTXN_8729570,Tea,5,1.5,7.5,UNKNOWN,In-store,2023-09-03\r\nTXN_7623634,Cake,2,3.0,,Credit Card,In-store,2023-07-11\r\nTXN_9336980,Salad,4,UNKNOWN,20.0,Cash,In-store,2023-06-06\r\nTXN_3424331,Cake,4,3.0,12.0,,,2023-01-18\r\nTXN_5072031,Cake,2,3.0,6.0,Cash,Takeaway,2023-03-23\r\nTXN_8687151,Salad,5,5.0,25.0,Cash,,2023-06-10\r\nTXN_4031509,,4,,16.0,Credit Card,Takeaway,2023-01-04\r\nTXN_5265095,Coffee,1,2.0,2.0,ERROR,,2023-06-23\r\nTXN_6541415,UNKNOWN,UNKNOWN,3.0,12.0,Cash,In-store,2023-11-25\r\nTXN_4108138,Coffee,5,2.0,10.0,Cash,,2023-08-03\r\nTXN_1909796,Smoothie,2,4.0,8.0,,Takeaway,2023-07-12\r\nTXN_1928241,Coffee,3,2.0,6.0,Cash,In-store,2023-04-30\r\nTXN_4283157,Salad,5,5.0,25.0,Digital Wallet,In-store,2023-11-25\r\nTXN_8013032,Coffee,2,2.0,4.0,Credit Card,,2023-03-07\r\nTXN_8301424,Juice,2,3.0,6.0,,ERROR,2023-06-27\r\nTXN_1093800,Sandwich,3,4.0,12.0,Cash,Takeaway,\r\nTXN_7965998,Juice,1,UNKNOWN,3.0,Credit Card,In-store,2023-11-02\r\nTXN_9238666,Cookie,1,UNKNOWN,1.0,ERROR,Takeaway,2023-07-31\r\nTXN_1631695,Tea,2,1.5,3.0,,In-store,2023-09-19\r\nTXN_1435086,Cake,5,,15.0,,ERROR,2023-02-09\r\nTXN_3226832,UNKNOWN,5,4.0,20.0,Cash,UNKNOWN,2023-09-04\r\nTXN_1648671,Sandwich,3,4.0,12.0,Cash,Takeaway,2023-05-21\r\nTXN_4062737,Cake,3,3.0,9.0,Cash,In-store,2023-07-02\r\nTXN_3494565,,2,4.0,8.0,ERROR,,2023-07-10\r\nTXN_9249507,Cookie,4,1.0,4.0,Credit Card,In-store,2023-11-21\r\nTXN_4689500,Sandwich,4,4.0,16.0,,,2023-12-02\r\nTXN_8989148,Tea,2,1.5,,,,2023-11-25\r\nTXN_8316826,Coffee,3,2.0,6.0,,In-store,2023-04-17\r\nTXN_9836934,Cookie,3,1.0,3.0,Digital Wallet,In-store,2023-03-13\r\nTXN_8005489,Cake,3,3.0,9.0,,In-store,2023-08-12\r\nTXN_6463132,Cookie,5,1.0,5.0,Credit Card,Takeaway,\r\nTXN_3925836,Cookie,3,1.0,3.0,Digital Wallet,In-store,2023-02-16\r\nTXN_1896955,Salad,ERROR,5.0,25.0,,In-store,2023-09-23\r\nTXN_5075974,Smoothie,ERROR,4.0,16.0,Digital Wallet,,2023-04-11\r\nTXN_3978874,Smoothie,5,4.0,20.0,Credit Card,In-store,2023-03-13\r\nTXN_8955912,Sandwich,1,4.0,4.0,,,2023-11-07\r\nTXN_1136554,Smoothie,3,4.0,12.0,UNKNOWN,Takeaway,2023-03-26\r\nTXN_8007337,Cake,2,3.0,6.0,Digital Wallet,Takeaway,2023-11-01\r\nTXN_8129834,Salad,1,5.0,5.0,Cash,,2023-07-22\r\nTXN_3831848,UNKNOWN,1,4.0,4.0,Digital Wallet,Takeaway,2023-11-03\r\nTXN_5365809,Cake,3,3.0,9.0,Cash,In-store,2023-09-14\r\nTXN_8166407,Smoothie,2,,8.0,,,2023-07-26\r\nTXN_6629480,Smoothie,5,4.0,20.0,Credit Card,In-store,2023-02-28\r\nTXN_3833797,Coffee,4,2.0,8.0,UNKNOWN,In-store,2023-01-27\r\nTXN_2643815,Cookie,UNKNOWN,1.0,3.0,ERROR,,2023-12-06\r\nTXN_2996519,Cake,5,3.0,15.0,Cash,,2023-01-19\r\nTXN_8810894,Smoothie,1,4.0,4.0,,,2023-02-20\r\nTXN_7412722,Juice,4,3.0,12.0,Cash,In-store,2023-04-07\r\nTXN_3937509,Smoothie,2,4.0,8.0,,In-store,2023-03-20\r\nTXN_6000201,Cookie,3,1.0,3.0,Cash,Takeaway,2023-02-16\r\nTXN_1714274,Cookie,4,1.0,4.0,,In-store,2023-12-27\r\nTXN_3800182,Tea,2,ERROR,3.0,Cash,In-store,2023-10-26\r\nTXN_5115080,,5,3.0,15.0,Credit Card,,2023-02-18\r\nTXN_9788956,Juice,ERROR,3.0,12.0,ERROR,,2023-04-11\r\nTXN_6311602,Juice,3,3.0,9.0,Credit Card,,2023-05-15\r\nTXN_2950680,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-12-10\r\nTXN_6749847,Cake,2,3.0,6.0,Credit Card,,2023-08-15\r\nTXN_2143187,Smoothie,1,4.0,4.0,,In-store,2023-04-21\r\nTXN_8964522,,3,3.0,9.0,Credit Card,Takeaway,2023-10-28\r\nTXN_4088917,Coffee,3,2.0,6.0,Cash,Takeaway,2023-02-04\r\nTXN_3779366,Cookie,1,1.0,1.0,Digital Wallet,In-store,2023-04-15\r\nTXN_7724048,Smoothie,1,4.0,4.0,ERROR,In-store,2023-11-12\r\nTXN_2698591,Tea,5,1.5,7.5,,,2023-08-05\r\nTXN_3171373,Smoothie,3,4.0,12.0,Credit Card,In-store,2023-05-10\r\nTXN_4129248,Sandwich,2,4.0,8.0,Credit Card,,ERROR\r\nTXN_6498163,Smoothie,5,4.0,20.0,,In-store,2023-07-15\r\nTXN_6717827,ERROR,3,5.0,15.0,Digital Wallet,,2023-11-15\r\nTXN_9089898,Salad,3,ERROR,15.0,Credit Card,,2023-01-11\r\nTXN_8587583,Cake,1,ERROR,3.0,,,2023-10-01\r\nTXN_8693704,Salad,ERROR,5.0,25.0,Cash,In-store,2023-05-04\r\nTXN_3857960,Salad,4,5.0,20.0,Cash,In-store,2023-04-26\r\nTXN_3499124,ERROR,4,4.0,16.0,Credit Card,,2023-08-25\r\nTXN_9250710,Salad,1,5.0,5.0,Cash,In-store,2023-05-28\r\nTXN_7058377,Juice,1,3.0,3.0,,Takeaway,2023-04-30\r\nTXN_6766492,Salad,1,5.0,5.0,,ERROR,2023-01-14\r\nTXN_9879996,Coffee,4,2.0,8.0,Digital Wallet,In-store,2023-03-01\r\nTXN_4291940,Cake,3,3.0,9.0,Credit Card,In-store,2023-11-13\r\nTXN_7433461,Cookie,2,1.0,2.0,Digital Wallet,,2023-07-09\r\nTXN_4068262,Salad,2,5.0,10.0,Credit Card,,2023-05-13\r\nTXN_5761073,Cookie,1,1.0,1.0,Cash,In-store,UNKNOWN\r\nTXN_5047447,Salad,1,5.0,5.0,Digital Wallet,Takeaway,2023-12-27\r\nTXN_6623508,Cookie,5,1.0,5.0,Digital Wallet,Takeaway,2023-05-18\r\nTXN_2651216,UNKNOWN,3,4.0,12.0,,,2023-04-04\r\nTXN_9350833,Cake,1,UNKNOWN,3.0,Cash,Takeaway,2023-01-17\r\nTXN_8377564,Cake,5,3.0,15.0,,In-store,2023-07-14\r\nTXN_7031118,Salad,1,5.0,5.0,Credit Card,ERROR,2023-03-29\r\nTXN_2230167,Cake,4,3.0,12.0,Digital Wallet,Takeaway,2023-09-22\r\nTXN_6446616,Tea,3,1.5,4.5,ERROR,,2023-09-30\r\nTXN_1721827,Cake,4,3.0,12.0,Digital Wallet,ERROR,2023-08-22\r\nTXN_6334895,Smoothie,1,4.0,4.0,Credit Card,ERROR,2023-07-27\r\nTXN_7077119,ERROR,1,4.0,4.0,Digital Wallet,In-store,2023-12-30\r\nTXN_8562645,Salad,ERROR,5.0,UNKNOWN,,In-store,2023-05-18\r\nTXN_4700144,Coffee,4,2.0,8.0,,In-store,2023-12-21\r\nTXN_5526852,Sandwich,5,4.0,,Digital Wallet,In-store,2023-09-28\r\nTXN_6846228,Salad,3,,15.0,,In-store,2023-11-16\r\nTXN_8570890,Juice,4,3.0,12.0,,,2023-04-14\r\nTXN_3205009,ERROR,2,1.5,3.0,Cash,In-store,2023-01-03\r\nTXN_3786188,Tea,3,1.5,4.5,Credit Card,In-store,2023-10-20\r\nTXN_4530804,Coffee,4,2.0,8.0,,,2023-01-12\r\nTXN_9642066,Sandwich,3,4.0,12.0,Credit Card,In-store,2023-08-31\r\nTXN_7328294,Juice,2,3.0,6.0,Cash,,2023-07-07\r\nTXN_1908636,Tea,2,1.5,3.0,,UNKNOWN,\r\nTXN_9238066,,5,1.5,7.5,Digital Wallet,In-store,2023-09-15\r\nTXN_5415901,Cake,2,3.0,6.0,Digital Wallet,,2023-10-21\r\nTXN_6714420,ERROR,2,3.0,6.0,Credit Card,Takeaway,2023-03-30\r\nTXN_6616971,Juice,2,3.0,6.0,Digital Wallet,Takeaway,2023-09-02\r\nTXN_7803615,Salad,3,5.0,15.0,Cash,In-store,2023-12-13\r\nTXN_7549542,Cookie,5,1.0,5.0,,Takeaway,\r\nTXN_3544789,Tea,4,1.5,ERROR,UNKNOWN,In-store,2023-07-14\r\nTXN_1583597,Salad,1,5.0,5.0,Cash,In-store,2023-05-10\r\nTXN_8472308,Cookie,2,1.0,2.0,Digital Wallet,Takeaway,2023-08-19\r\nTXN_1967565,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-03-31\r\nTXN_2029497,Sandwich,2,4.0,8.0,Cash,Takeaway,2023-01-06\r\nTXN_8929774,ERROR,3,3.0,9.0,Cash,,2023-10-02\r\nTXN_5003018,Cookie,4,1.0,UNKNOWN,Digital Wallet,,UNKNOWN\r\nTXN_7852990,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-07-10\r\nTXN_2534066,Salad,2,5.0,10.0,Cash,,2023-10-13\r\nTXN_2059647,Tea,1,1.5,1.5,Digital Wallet,In-store,2023-05-29\r\nTXN_2485183,Smoothie,5,4.0,20.0,Cash,In-store,2023-07-07\r\nTXN_7374846,Sandwich,1,4.0,4.0,Credit Card,UNKNOWN,2023-05-29\r\nTXN_9401522,Sandwich,4,4.0,16.0,Digital Wallet,In-store,2023-11-16\r\nTXN_8250651,Sandwich,4,4.0,16.0,Digital Wallet,In-store,2023-03-13\r\nTXN_7191245,Cake,4,3.0,12.0,,Takeaway,2023-05-22\r\nTXN_8982764,Cake,5,3.0,15.0,Digital Wallet,Takeaway,2023-11-23\r\nTXN_8669422,,4,3.0,12.0,Cash,Takeaway,2023-10-15\r\nTXN_1153869,Smoothie,5,4.0,20.0,Credit Card,Takeaway,2023-11-03\r\nTXN_5043774,Sandwich,3,4.0,12.0,Cash,,2023-06-08\r\nTXN_1746320,Salad,1,5.0,5.0,Cash,,2023-11-14\r\nTXN_1077129,Cookie,1,1.0,1.0,,In-store,2023-09-12\r\nTXN_4865338,Sandwich,UNKNOWN,4.0,16.0,,In-store,2023-11-26\r\nTXN_5616583,Smoothie,1,4.0,4.0,,,2023-10-13\r\nTXN_2078474,Cookie,2,1.0,2.0,,Takeaway,2023-11-03\r\nTXN_2130245,Smoothie,5,4.0,20.0,Credit Card,,2023-11-13\r\nTXN_3229409,Juice,UNKNOWN,3.0,UNKNOWN,Cash,Takeaway,2023-04-15\r\nTXN_9076216,Cake,1,3.0,3.0,Cash,,2023-12-17\r\nTXN_6371987,Tea,5,1.5,ERROR,UNKNOWN,Takeaway,2023-03-13\r\nTXN_9913877,ERROR,2,2.0,4.0,Credit Card,,2023-05-09\r\nTXN_2084377,Smoothie,1,4.0,4.0,Credit Card,ERROR,2023-10-22\r\nTXN_1842675,ERROR,4,1.0,4.0,Credit Card,Takeaway,2023-06-23\r\nTXN_8605813,Cookie,1,1.0,1.0,,,2023-06-30\r\nTXN_9755352,Sandwich,5,4.0,20.0,,In-store,2023-05-13\r\nTXN_7550498,Juice,5,3.0,15.0,,In-store,ERROR\r\nTXN_2305908,Coffee,UNKNOWN,2.0,8.0,Cash,,2023-04-25\r\nTXN_6953697,UNKNOWN,3,4.0,12.0,,Takeaway,2023-05-27\r\nTXN_3495950,,4,ERROR,6.0,Credit Card,In-store,2023-02-19\r\nTXN_7557340,Tea,5,1.5,7.5,Credit Card,In-store,2023-12-11\r\nTXN_1157817,Smoothie,1,4.0,4.0,Digital Wallet,In-store,2023-04-25\r\nTXN_2020318,Tea,3,1.5,4.5,Digital Wallet,In-store,2023-10-12\r\nTXN_8692094,Coffee,5,2.0,10.0,,Takeaway,2023-08-30\r\nTXN_5307411,Cake,3,3.0,ERROR,Digital Wallet,Takeaway,2023-10-21\r\nTXN_9703120,Coffee,3,2.0,6.0,Credit Card,,2023-11-02\r\nTXN_1289133,Juice,1,3.0,3.0,Cash,UNKNOWN,2023-09-19\r\nTXN_2031459,Cake,3,3.0,9.0,Cash,Takeaway,2023-07-04\r\nTXN_1333682,Smoothie,1,4.0,4.0,Digital Wallet,,2023-01-28\r\nTXN_2256622,Cookie,2,,2.0,Cash,In-store,2023-10-04\r\nTXN_1623966,Tea,2,1.5,3.0,Cash,Takeaway,UNKNOWN\r\nTXN_4912930,Smoothie,3,4.0,12.0,Credit Card,In-store,2023-02-26\r\nTXN_4942692,Coffee,2,2.0,4.0,,Takeaway,2023-01-15\r\nTXN_3723007,Tea,3,1.5,4.5,Digital Wallet,In-store,2023-05-18\r\nTXN_7922392,Sandwich,3,4.0,12.0,,,2023-05-03\r\nTXN_7498727,Salad,3,5.0,15.0,Cash,,2023-11-06\r\nTXN_1222338,Cookie,1,1.0,1.0,,In-store,2023-10-11\r\nTXN_6878866,Smoothie,3,4.0,12.0,Credit Card,,2023-02-25\r\nTXN_1260335,Cookie,4,1.0,4.0,Digital Wallet,In-store,\r\nTXN_9223242,Smoothie,2,4.0,8.0,,,2023-09-10\r\nTXN_6244211,Smoothie,2,4.0,8.0,,,2023-08-11\r\nTXN_5446858,,1,1.0,1.0,Cash,In-store,2023-11-07\r\nTXN_4612864,Tea,3,1.5,4.5,,,2023-02-14\r\nTXN_5411381,Cookie,ERROR,1.0,1.0,,,2023-04-28\r\nTXN_3047598,Cookie,1,1.0,1.0,,,2023-09-06\r\nTXN_5754317,Coffee,2,,4.0,Credit Card,Takeaway,2023-01-10\r\nTXN_7496926,Sandwich,3,4.0,12.0,ERROR,In-store,2023-04-23\r\nTXN_1726858,Smoothie,3,4.0,12.0,Cash,In-store,\r\nTXN_7559388,Salad,4,5.0,20.0,Digital Wallet,Takeaway,2023-02-26\r\nTXN_8540499,Cookie,3,1.0,3.0,Cash,In-store,2023-01-22\r\nTXN_4225756,Cookie,3,1.0,3.0,,In-store,2023-03-10\r\nTXN_6795640,Cookie,4,1.0,4.0,Digital Wallet,Takeaway,2023-01-28\r\nTXN_6702428,Coffee,5,2.0,10.0,Cash,Takeaway,2023-08-11\r\nTXN_8955259,ERROR,2,4.0,8.0,Credit Card,,2023-11-18\r\nTXN_4639319,Coffee,5,2.0,10.0,Cash,,2023-01-09\r\nTXN_5997803,Coffee,5,2.0,10.0,,In-store,2023-12-03\r\nTXN_1340956,ERROR,4,2.0,8.0,,,2023-10-26\r\nTXN_1259671,Sandwich,UNKNOWN,4.0,12.0,Digital Wallet,In-store,2023-10-08\r\nTXN_8319993,Juice,1,3.0,3.0,Digital Wallet,,2023-08-06\r\nTXN_8894157,Sandwich,4,4.0,16.0,Credit Card,,ERROR\r\nTXN_5523450,Salad,5,5.0,25.0,Credit Card,Takeaway,2023-07-02\r\nTXN_7838964,Sandwich,3,4.0,12.0,Credit Card,In-store,2023-06-15\r\nTXN_2773987,Smoothie,5,4.0,20.0,ERROR,,2023-01-11\r\nTXN_1158829,Tea,1,UNKNOWN,1.5,Credit Card,,2023-10-02\r\nTXN_2523298,,4,,6.0,ERROR,In-store,2023-03-25\r\nTXN_8685737,Smoothie,2,4.0,8.0,,In-store,2023-11-02\r\nTXN_5634135,Cookie,2,UNKNOWN,2.0,,ERROR,2023-01-27\r\nTXN_1524626,Smoothie,2,4.0,8.0,Digital Wallet,,2023-12-29\r\nTXN_7275407,Smoothie,2,4.0,8.0,Digital Wallet,In-store,2023-10-20\r\nTXN_2889622,Juice,4,3.0,12.0,Credit Card,,2023-11-01\r\nTXN_6849113,Cookie,ERROR,1.0,1.0,Credit Card,,2023-07-14\r\nTXN_2265316,Cookie,,1.0,3.0,Credit Card,In-store,2023-12-29\r\nTXN_9472241,Salad,3,5.0,15.0,Cash,Takeaway,2023-06-30\r\nTXN_7345414,Salad,1,,5.0,,UNKNOWN,2023-02-15\r\nTXN_4473352,Cake,1,3.0,3.0,UNKNOWN,In-store,2023-11-16\r\nTXN_2814363,Tea,2,1.5,3.0,,,2023-07-02\r\nTXN_1846004,Juice,3,3.0,9.0,Cash,In-store,2023-05-21\r\nTXN_7140471,Cake,1,3.0,3.0,Credit Card,,2023-05-25\r\nTXN_3119542,Smoothie,1,4.0,4.0,Credit Card,,2023-10-31\r\nTXN_7773968,Sandwich,5,4.0,20.0,Digital Wallet,Takeaway,2023-02-24\r\nTXN_9081088,Tea,2,1.5,3.0,Cash,Takeaway,2023-02-27\r\nTXN_8559167,Sandwich,5,4.

In [ ]:
df1= pd.read_csv("/content/dirty_cafe_sales.csv")

In [ ]:
df1

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
df1.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [ ]:
df1.tail()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

Data Inspection

In [ ]:
df.shape

df.info()
df.columns
df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             6 non-null      int64
 1   monthly_salary  6 non-null      float64
 2   experience      6 non-null      int64
 3   bonus           6 non-null      float64
 4   salary_k        6 non-null      float64
dtypes: float64(3), int64(2)
memory usage: 288.0 bytes

            age  monthly_salary  experience         bonus       salary_k
count   6.00000    6.000000e+00    6.000000  6.000000e+00       6.000000
mean   25.50000    9.336333e+07    3.666667  9.336333e+06   93363.333333
std     5.00999    2.237408e+08    1.751190  2.237408e+07  223740.803848
min    21.00000    3.000000e+04    1.000000  3.000000e+03      30.000000
25%    22.50000    4.250000e+04    3.000000  4.250000e+03      42.500000
50%    24.50000    5.500000e+04    3.500000  5.500000e+03      55.000000
75%    25.75000    7.515000e+06    4.750000  7.515000e+05    7515.000000
max    35.00000    5.500000e+08    6.000000  5.500000e+07  550000.000000

In [ ]:
df1.shape

(10000, 8)

In [ ]:
df1.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [ ]:
df1.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

handling missing values

In [ ]:
# find missing values
df1.isna()

#sum of missing values
df1.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
df1

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
#Drop the missing values
#df1.dropna()

In [ ]:
df1

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
#fill the missing values
df1.fillna(df1.median())

TypeError: Cannot convert [['TXN_1961373' 'TXN_4977031' 'TXN_4271903' ... 'TXN_5255387'
  'TXN_7695629' 'TXN_6170729']
 ['Coffee' 'Cake' 'Cookie' ... 'Coffee' 'Cookie' 'Sandwich']
 ['2' '4' '4' ... '4' '3' '3']
 ...
 ['Credit Card' 'Cash' 'Credit Card' ... 'Digital Wallet'
  'Digital Wallet' 'Cash']
 ['Takeaway' 'In-store' 'In-store' ... nan nan 'In-store']
 ['2023-09-08' '2023-05-16' '2023-07-19' ... '2023-03-02' '2023-12-02'
  '2023-11-07']] to numeric

Sorting and Grouping

In [ ]:
df.sort_values(by="salary", ascending=False)

KeyError: 'salary'

In [ ]:
df.groupby("country")["salary"].mean()

Converting pandas to numpy

In [ ]:
X = df[["age", "salary"]].values
y = df["target"].values

KeyError: "['salary'] not in index"